// Copyright 2026 The ninsun-labs Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: proto/v1/bridge.proto

package bridgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SubscribeRequest is sent once at the start of any of the three
// streams. The same shape is reused for all three to keep the wire
// surface tight; per-stream filters are optional and ignored on
// streams where they don't apply.
type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SubscriberId is the operator-local identifier (e.g.
	// "tenant-escape-<node>") used for buffer accounting + metrics.
	// Multiple subscribers with the same id are allowed; events are
	// fanned out independently.
	SubscriberId string `protobuf:"bytes,1,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	// MaxEventsPerSec asks the server to throttle to N events/second
	// for this subscriber. Zero = no client-side rate limit (server
	// still applies its own backpressure cap).
	MaxEventsPerSec uint32 `protobuf:"varint,2,opt,name=max_events_per_sec,json=maxEventsPerSec,proto3" json:"max_events_per_sec,omitempty"`
	// TargetPod, when non-zero, restricts the stream to events whose
	// origin Pod matches the namespace+name pair. Required on
	// StreamFileOpen, optional on the others.
	TargetPod     *PodRef `protobuf:"bytes,3,opt,name=target_pod,json=targetPod,proto3" json:"target_pod,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_v1_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

func (x *SubscribeRequest) GetMaxEventsPerSec() uint32 {
	if x != nil {
		return x.MaxEventsPerSec
	}
	return 0
}

func (x *SubscribeRequest) GetTargetPod() *PodRef {
	if x != nil {
		return x.TargetPod
	}
	return nil
}

// PodRef is a namespace+name pair the bridge correlates against
// Tetragon's PodInfo block on every event.
type PodRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodRef) Reset() {
	*x = PodRef{}
	mi := &file_proto_v1_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodRef) ProtoMessage() {}

func (x *PodRef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodRef.ProtoReflect.Descriptor instead.
func (*PodRef) Descriptor() ([]byte, []int) {
	return file_proto_v1_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *PodRef) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PodRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ProcessInfo is the resolver-style bundle every typed event carries.
// Populated from Tetragon's process tree resolver on the
// observing node.
type ProcessInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PID inside the host PID namespace.
	Pid uint32 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	// BinaryPath as seen from the host (resolved through
	// /proc/<pid>/exe).
	BinaryPath string `protobuf:"bytes,2,opt,name=binary_path,json=binaryPath,proto3" json:"binary_path,omitempty"`
	// ContainerId is the runtime-specific container ID
	// (containerd:// stripped). Empty when the process is on
	// the host.
	ContainerId string `protobuf:"bytes,3,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// Pod is the resolver-enriched namespace/name. Empty for
	// host-only processes.
	Pod *PodRef `protobuf:"bytes,4,opt,name=pod,proto3" json:"pod,omitempty"`
	// ServiceAccount username inferred from the Pod's SA token.
	// Format: system:serviceaccount:<ns>:<name>.
	ServiceAccount string `protobuf:"bytes,5,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_proto_v1_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_proto_v1_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessInfo) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessInfo) GetBinaryPath() string {
	if x != nil {
		return x.BinaryPath
	}
	return ""
}

func (x *ProcessInfo) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ProcessInfo) GetPod() *PodRef {
	if x != nil {
		return x.Pod
	}
	return nil
}

func (x *ProcessInfo) GetServiceAccount() string {
	if x != nil {
		return x.ServiceAccount
	}
	return ""
}

// ProcessExec is one PROCESS_EXEC observation.
type ProcessExec struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	NodeName  string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Process   *ProcessInfo           `protobuf:"bytes,3,opt,name=process,proto3" json:"process,omitempty"`
	// ParentPid is the pid of the exec's parent process.
	ParentPid uint32 `protobuf:"varint,4,opt,name=parent_pid,json=parentPid,proto3" json:"parent_pid,omitempty"`
	// Argv is the full argument vector as Tetragon captured it.
	Argv []string `protobuf:"bytes,5,rep,name=argv,proto3" json:"argv,omitempty"`
	// EnvHash is a SHA-256 over the env block (Tetragon does not
	// forward the env values themselves to keep the wire surface
	// small + privacy-clean).
	EnvHash string `protobuf:"bytes,6,opt,name=env_hash,json=envHash,proto3" json:"env_hash,omitempty"`
	// Capabilities is the effective capability set at exec time.
	Capabilities []string `protobuf:"bytes,7,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// UidGid is the (uid, gid) pair the binary launched as.
	Uid           uint32 `protobuf:"varint,8,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint32 `protobuf:"varint,9,opt,name=gid,proto3" json:"gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessExec) Reset() {
	*x = ProcessExec{}
	mi := &file_proto_v1_bridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessExec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessExec) ProtoMessage() {}

func (x *ProcessExec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_bridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessExec.ProtoReflect.Descriptor instead.
func (*ProcessExec) Descriptor() ([]byte, []int) {
	return file_proto_v1_bridge_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessExec) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ProcessExec) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *ProcessExec) GetProcess() *ProcessInfo {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *ProcessExec) GetParentPid() uint32 {
	if x != nil {
		return x.ParentPid
	}
	return 0
}

func (x *ProcessExec) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *ProcessExec) GetEnvHash() string {
	if x != nil {
		return x.EnvHash
	}
	return ""
}

func (x *ProcessExec) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ProcessExec) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ProcessExec) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

// DNSQuery is one kprobe-observed DNS lookup. Subset of the
// CoreDNS plugin DNSEvent contract - only the fields Tetragon
// can populate from kprobe data.
type DNSQuery struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	NodeName  string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Process   *ProcessInfo           `protobuf:"bytes,3,opt,name=process,proto3" json:"process,omitempty"`
	// Qname is the question name (FQDN, lowercased).
	Qname string `protobuf:"bytes,4,opt,name=qname,proto3" json:"qname,omitempty"`
	// Qtype is the RFC 1035 query type ("A", "AAAA", "TXT", ...).
	Qtype string `protobuf:"bytes,5,opt,name=qtype,proto3" json:"qtype,omitempty"`
	// DstIP is the upstream DNS server IP. 4-byte (v4) or 16-byte (v6).
	DstIp []byte `protobuf:"bytes,6,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	// DstPort is the destination port (53 in normal cluster DNS).
	DstPort       uint32 `protobuf:"varint,7,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSQuery) Reset() {
	*x = DNSQuery{}
	mi := &file_proto_v1_bridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSQuery) ProtoMessage() {}

func (x *DNSQuery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_bridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSQuery.ProtoReflect.Descriptor instead.
func (*DNSQuery) Descriptor() ([]byte, []int) {
	return file_proto_v1_bridge_proto_rawDescGZIP(), []int{4}
}

func (x *DNSQuery) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DNSQuery) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *DNSQuery) GetProcess() *ProcessInfo {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *DNSQuery) GetQname() string {
	if x != nil {
		return x.Qname
	}
	return ""
}

func (x *DNSQuery) GetQtype() string {
	if x != nil {
		return x.Qtype
	}
	return ""
}

func (x *DNSQuery) GetDstIp() []byte {
	if x != nil {
		return x.DstIp
	}
	return nil
}

func (x *DNSQuery) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

// FileOpen is one open() observation. Used by seccomp-gen to record
// the syscall + path surface during a training run.
type FileOpen struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	NodeName  string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Process   *ProcessInfo           `protobuf:"bytes,3,opt,name=process,proto3" json:"process,omitempty"`
	// Path is the absolute path the syscall was made against.
	Path string `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	// Flags is the open(2) flags bitmap (O_RDONLY, O_WRONLY, ...).
	Flags uint32 `protobuf:"varint,5,opt,name=flags,proto3" json:"flags,omitempty"`
	// Mode is the open(2) mode bitmap when O_CREAT is set; 0 otherwise.
	Mode uint32 `protobuf:"varint,6,opt,name=mode,proto3" json:"mode,omitempty"`
	// Returncode is the syscall return value. < 0 indicates error
	// (-EACCES, -ENOENT, ...).
	Returncode    int32 `protobuf:"varint,7,opt,name=returncode,proto3" json:"returncode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileOpen) Reset() {
	*x = FileOpen{}
	mi := &file_proto_v1_bridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOpen) ProtoMessage() {}

func (x *FileOpen) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_bridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileOpen.ProtoReflect.Descriptor instead.
func (*FileOpen) Descriptor() ([]byte, []int) {
	return file_proto_v1_bridge_proto_rawDescGZIP(), []int{5}
}

func (x *FileOpen) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *FileOpen) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *FileOpen) GetProcess() *ProcessInfo {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *FileOpen) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileOpen) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *FileOpen) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileOpen) GetReturncode() int32 {
	if x != nil {
		return x.Returncode
	}
	return 0
}

var File_proto_v1_bridge_proto protoreflect.FileDescriptor

const file_proto_v1_bridge_proto_rawDesc = "" +
	"\n" +
	"\x15proto/v1/bridge.proto\x12\x19ninsun.tetragon_bridge.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa6\x01\n" +
	"\x10SubscribeRequest\x12#\n" +
	"\rsubscriber_id\x18\x01 \x01(\tR\fsubscriberId\x12+\n" +
	"\x12max_events_per_sec\x18\x02 \x01(\rR\x0fmaxEventsPerSec\x12@\n" +
	"\n" +
	"target_pod\x18\x03 \x01(\v2!.ninsun.tetragon_bridge.v1.PodRefR\ttargetPod\":\n" +
	"\x06PodRef\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xc1\x01\n" +
	"\vProcessInfo\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12\x1f\n" +
	"\vbinary_path\x18\x02 \x01(\tR\n" +
	"binaryPath\x12!\n" +
	"\fcontainer_id\x18\x03 \x01(\tR\vcontainerId\x123\n" +
	"\x03pod\x18\x04 \x01(\v2!.ninsun.tetragon_bridge.v1.PodRefR\x03pod\x12'\n" +
	"\x0fservice_account\x18\x05 \x01(\tR\x0eserviceAccount\"\xbc\x02\n" +
	"\vProcessExec\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12@\n" +
	"\aprocess\x18\x03 \x01(\v2&.ninsun.tetragon_bridge.v1.ProcessInfoR\aprocess\x12\x1d\n" +
	"\n" +
	"parent_pid\x18\x04 \x01(\rR\tparentPid\x12\x12\n" +
	"\x04argv\x18\x05 \x03(\tR\x04argv\x12\x19\n" +
	"\benv_hash\x18\x06 \x01(\tR\aenvHash\x12\"\n" +
	"\fcapabilities\x18\a \x03(\tR\fcapabilities\x12\x10\n" +
	"\x03uid\x18\b \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\t \x01(\rR\x03gid\"\x81\x02\n" +
	"\bDNSQuery\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12@\n" +
	"\aprocess\x18\x03 \x01(\v2&.ninsun.tetragon_bridge.v1.ProcessInfoR\aprocess\x12\x14\n" +
	"\x05qname\x18\x04 \x01(\tR\x05qname\x12\x14\n" +
	"\x05qtype\x18\x05 \x01(\tR\x05qtype\x12\x15\n" +
	"\x06dst_ip\x18\x06 \x01(\fR\x05dstIp\x12\x19\n" +
	"\bdst_port\x18\a \x01(\rR\adstPort\"\x81\x02\n" +
	"\bFileOpen\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12@\n" +
	"\aprocess\x18\x03 \x01(\v2&.ninsun.tetragon_bridge.v1.ProcessInfoR\aprocess\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x14\n" +
	"\x05flags\x18\x05 \x01(\rR\x05flags\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\rR\x04mode\x12\x1e\n" +
	"\n" +
	"returncode\x18\a \x01(\x05R\n" +
	"returncode2\xc8\x02\n" +
	"\x0eTetragonBridge\x12j\n" +
	"\x11StreamProcessExec\x12+.ninsun.tetragon_bridge.v1.SubscribeRequest\x1a&.ninsun.tetragon_bridge.v1.ProcessExec0\x01\x12d\n" +
	"\x0eStreamDNSQuery\x12+.ninsun.tetragon_bridge.v1.SubscribeRequest\x1a#.ninsun.tetragon_bridge.v1.DNSQuery0\x01\x12d\n" +
	"\x0eStreamFileOpen\x12+.ninsun.tetragon_bridge.v1.SubscribeRequest\x1a#.ninsun.tetragon_bridge.v1.FileOpen0\x01B:Z8github.com/ninsun-labs/tetragon-bridge/proto/v1;bridgev1b\x06proto3"

var (
	file_proto_v1_bridge_proto_rawDescOnce sync.Once
	file_proto_v1_bridge_proto_rawDescData []byte
)

func file_proto_v1_bridge_proto_rawDescGZIP() []byte {
	file_proto_v1_bridge_proto_rawDescOnce.Do(func() {
		file_proto_v1_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_bridge_proto_rawDesc), len(file_proto_v1_bridge_proto_rawDesc)))
	})
	return file_proto_v1_bridge_proto_rawDescData
}

var file_proto_v1_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_v1_bridge_proto_goTypes = []any{
	(*SubscribeRequest)(nil),      // 0: ninsun.tetragon_bridge.v1.SubscribeRequest
	(*PodRef)(nil),                // 1: ninsun.tetragon_bridge.v1.PodRef
	(*ProcessInfo)(nil),           // 2: ninsun.tetragon_bridge.v1.ProcessInfo
	(*ProcessExec)(nil),           // 3: ninsun.tetragon_bridge.v1.ProcessExec
	(*DNSQuery)(nil),              // 4: ninsun.tetragon_bridge.v1.DNSQuery
	(*FileOpen)(nil),              // 5: ninsun.tetragon_bridge.v1.FileOpen
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_proto_v1_bridge_proto_depIdxs = []int32{
	1,  // 0: ninsun.tetragon_bridge.v1.SubscribeRequest.target_pod:type_name -> ninsun.tetragon_bridge.v1.PodRef
	1,  // 1: ninsun.tetragon_bridge.v1.ProcessInfo.pod:type_name -> ninsun.tetragon_bridge.v1.PodRef
	6,  // 2: ninsun.tetragon_bridge.v1.ProcessExec.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 3: ninsun.tetragon_bridge.v1.ProcessExec.process:type_name -> ninsun.tetragon_bridge.v1.ProcessInfo
	6,  // 4: ninsun.tetragon_bridge.v1.DNSQuery.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 5: ninsun.tetragon_bridge.v1.DNSQuery.process:type_name -> ninsun.tetragon_bridge.v1.ProcessInfo
	6,  // 6: ninsun.tetragon_bridge.v1.FileOpen.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 7: ninsun.tetragon_bridge.v1.FileOpen.process:type_name -> ninsun.tetragon_bridge.v1.ProcessInfo
	0,  // 8: ninsun.tetragon_bridge.v1.TetragonBridge.StreamProcessExec:input_type -> ninsun.tetragon_bridge.v1.SubscribeRequest
	0,  // 9: ninsun.tetragon_bridge.v1.TetragonBridge.StreamDNSQuery:input_type -> ninsun.tetragon_bridge.v1.SubscribeRequest
	0,  // 10: ninsun.tetragon_bridge.v1.TetragonBridge.StreamFileOpen:input_type -> ninsun.tetragon_bridge.v1.SubscribeRequest
	3,  // 11: ninsun.tetragon_bridge.v1.TetragonBridge.StreamProcessExec:output_type -> ninsun.tetragon_bridge.v1.ProcessExec
	4,  // 12: ninsun.tetragon_bridge.v1.TetragonBridge.StreamDNSQuery:output_type -> ninsun.tetragon_bridge.v1.DNSQuery
	5,  // 13: ninsun.tetragon_bridge.v1.TetragonBridge.StreamFileOpen:output_type -> ninsun.tetragon_bridge.v1.FileOpen
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_v1_bridge_proto_init() }
func file_proto_v1_bridge_proto_init() {
	if File_proto_v1_bridge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_bridge_proto_rawDesc), len(file_proto_v1_bridge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_bridge_proto_goTypes,
		DependencyIndexes: file_proto_v1_bridge_proto_depIdxs,
		MessageInfos:      file_proto_v1_bridge_proto_msgTypes,
	}.Build()
	File_proto_v1_bridge_proto = out.File
	file_proto_v1_bridge_proto_goTypes = nil
	file_proto_v1_bridge_proto_depIdxs = nil
}
