// Copyright 2026 The ninsun-labs Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: proto/v1/bridge.proto

package bridgev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TetragonBridge_StreamProcessExec_FullMethodName = "/ninsun.tetragon_bridge.v1.TetragonBridge/StreamProcessExec"
	TetragonBridge_StreamDNSQuery_FullMethodName    = "/ninsun.tetragon_bridge.v1.TetragonBridge/StreamDNSQuery"
	TetragonBridge_StreamFileOpen_FullMethodName    = "/ninsun.tetragon_bridge.v1.TetragonBridge/StreamFileOpen"
)

// TetragonBridgeClient is the client API for TetragonBridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TetragonBridge fronts the upstream Tetragon Hubble GetEvents API and
// re-exposes a small, typed surface tailored to ugallu detector
// workloads. The bridge consumes the raw event firehose once
// (single Tetragon connection per node), filters down to the kinds
// the operators need, and fans out to N typed subscribers each with
// its own per-subscriber buffer + rate limit.
//
// Three streams are exposed in v0.1.0:
//   - StreamProcessExec: every PROCESS_EXEC (process tree edges,
//     used by tenant-escape to detect privileged exec inside Pods).
//   - StreamDNSQuery: kprobe-derived DNS lookups (used as the
//     dns-detect Tetragon kprobe fallback when CoreDNS plugin is
//     unreachable).
//   - StreamFileOpen: open() syscall observations (used by
//     seccomp-gen to record syscall surface during a training run).
//
// All streams are server-streaming. Backpressure: when a subscriber
// can't keep up, the bridge keeps the last 10 000 events in a
// per-subscriber ring before drop-oldest-first; the metric
// ugallu_tetragon_bridge_dropped_total{stream,subscriber_id,reason}
// surfaces the drop count for ops review.
type TetragonBridgeClient interface {
	// StreamProcessExec emits one ProcessExec per PROCESS_EXEC event
	// observed by Tetragon (after node-local rate limiting).
	StreamProcessExec(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProcessExec], error)
	// StreamDNSQuery emits one DNSQuery per kprobe-observed DNS
	// lookup. Used by dns-detect when its primary CoreDNS plugin
	// backend is unreachable (degraded mode).
	StreamDNSQuery(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DNSQuery], error)
	// StreamFileOpen emits one FileOpen per open() syscall. Filtered
	// server-side by Subject.target_pod when set on SubscribeRequest;
	// unfiltered subscribes are rejected on a node-local DaemonSet
	// because the volume would saturate the bridge.
	StreamFileOpen(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileOpen], error)
}

type tetragonBridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewTetragonBridgeClient(cc grpc.ClientConnInterface) TetragonBridgeClient {
	return &tetragonBridgeClient{cc}
}

func (c *tetragonBridgeClient) StreamProcessExec(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProcessExec], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TetragonBridge_ServiceDesc.Streams[0], TetragonBridge_StreamProcessExec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, ProcessExec]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TetragonBridge_StreamProcessExecClient = grpc.ServerStreamingClient[ProcessExec]

func (c *tetragonBridgeClient) StreamDNSQuery(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DNSQuery], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TetragonBridge_ServiceDesc.Streams[1], TetragonBridge_StreamDNSQuery_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, DNSQuery]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TetragonBridge_StreamDNSQueryClient = grpc.ServerStreamingClient[DNSQuery]

func (c *tetragonBridgeClient) StreamFileOpen(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileOpen], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TetragonBridge_ServiceDesc.Streams[2], TetragonBridge_StreamFileOpen_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, FileOpen]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TetragonBridge_StreamFileOpenClient = grpc.ServerStreamingClient[FileOpen]

// TetragonBridgeServer is the server API for TetragonBridge service.
// All implementations must embed UnimplementedTetragonBridgeServer
// for forward compatibility.
//
// TetragonBridge fronts the upstream Tetragon Hubble GetEvents API and
// re-exposes a small, typed surface tailored to ugallu detector
// workloads. The bridge consumes the raw event firehose once
// (single Tetragon connection per node), filters down to the kinds
// the operators need, and fans out to N typed subscribers each with
// its own per-subscriber buffer + rate limit.
//
// Three streams are exposed in v0.1.0:
//   - StreamProcessExec: every PROCESS_EXEC (process tree edges,
//     used by tenant-escape to detect privileged exec inside Pods).
//   - StreamDNSQuery: kprobe-derived DNS lookups (used as the
//     dns-detect Tetragon kprobe fallback when CoreDNS plugin is
//     unreachable).
//   - StreamFileOpen: open() syscall observations (used by
//     seccomp-gen to record syscall surface during a training run).
//
// All streams are server-streaming. Backpressure: when a subscriber
// can't keep up, the bridge keeps the last 10 000 events in a
// per-subscriber ring before drop-oldest-first; the metric
// ugallu_tetragon_bridge_dropped_total{stream,subscriber_id,reason}
// surfaces the drop count for ops review.
type TetragonBridgeServer interface {
	// StreamProcessExec emits one ProcessExec per PROCESS_EXEC event
	// observed by Tetragon (after node-local rate limiting).
	StreamProcessExec(*SubscribeRequest, grpc.ServerStreamingServer[ProcessExec]) error
	// StreamDNSQuery emits one DNSQuery per kprobe-observed DNS
	// lookup. Used by dns-detect when its primary CoreDNS plugin
	// backend is unreachable (degraded mode).
	StreamDNSQuery(*SubscribeRequest, grpc.ServerStreamingServer[DNSQuery]) error
	// StreamFileOpen emits one FileOpen per open() syscall. Filtered
	// server-side by Subject.target_pod when set on SubscribeRequest;
	// unfiltered subscribes are rejected on a node-local DaemonSet
	// because the volume would saturate the bridge.
	StreamFileOpen(*SubscribeRequest, grpc.ServerStreamingServer[FileOpen]) error
	mustEmbedUnimplementedTetragonBridgeServer()
}

// UnimplementedTetragonBridgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTetragonBridgeServer struct{}

func (UnimplementedTetragonBridgeServer) StreamProcessExec(*SubscribeRequest, grpc.ServerStreamingServer[ProcessExec]) error {
	return status.Error(codes.Unimplemented, "method StreamProcessExec not implemented")
}
func (UnimplementedTetragonBridgeServer) StreamDNSQuery(*SubscribeRequest, grpc.ServerStreamingServer[DNSQuery]) error {
	return status.Error(codes.Unimplemented, "method StreamDNSQuery not implemented")
}
func (UnimplementedTetragonBridgeServer) StreamFileOpen(*SubscribeRequest, grpc.ServerStreamingServer[FileOpen]) error {
	return status.Error(codes.Unimplemented, "method StreamFileOpen not implemented")
}
func (UnimplementedTetragonBridgeServer) mustEmbedUnimplementedTetragonBridgeServer() {}
func (UnimplementedTetragonBridgeServer) testEmbeddedByValue()                        {}

// UnsafeTetragonBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TetragonBridgeServer will
// result in compilation errors.
type UnsafeTetragonBridgeServer interface {
	mustEmbedUnimplementedTetragonBridgeServer()
}

func RegisterTetragonBridgeServer(s grpc.ServiceRegistrar, srv TetragonBridgeServer) {
	// If the following call panics, it indicates UnimplementedTetragonBridgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TetragonBridge_ServiceDesc, srv)
}

func _TetragonBridge_StreamProcessExec_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TetragonBridgeServer).StreamProcessExec(m, &grpc.GenericServerStream[SubscribeRequest, ProcessExec]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TetragonBridge_StreamProcessExecServer = grpc.ServerStreamingServer[ProcessExec]

func _TetragonBridge_StreamDNSQuery_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TetragonBridgeServer).StreamDNSQuery(m, &grpc.GenericServerStream[SubscribeRequest, DNSQuery]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TetragonBridge_StreamDNSQueryServer = grpc.ServerStreamingServer[DNSQuery]

func _TetragonBridge_StreamFileOpen_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TetragonBridgeServer).StreamFileOpen(m, &grpc.GenericServerStream[SubscribeRequest, FileOpen]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TetragonBridge_StreamFileOpenServer = grpc.ServerStreamingServer[FileOpen]

// TetragonBridge_ServiceDesc is the grpc.ServiceDesc for TetragonBridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TetragonBridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ninsun.tetragon_bridge.v1.TetragonBridge",
	HandlerType: (*TetragonBridgeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamProcessExec",
			Handler:       _TetragonBridge_StreamProcessExec_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamDNSQuery",
			Handler:       _TetragonBridge_StreamDNSQuery_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamFileOpen",
			Handler:       _TetragonBridge_StreamFileOpen_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/v1/bridge.proto",
}
